# 存储项目配置文件

# 服务端运行地址
application_port: "9999"

# mysql配置文件
mysql:
  host: "127.0.0.1"   # mysql地址
  port: "3306"   # 运行端口
  username: "root" # 用户名
  password: "Or2452020438" # 密码
  database: "BlockchainCarelnsureHub" # 数据库

# 合约地址
contract_address: "0x233f48e4Da733E3174Fd8c68E69E962ee61b8Ed7"

alipay:
  app_id: ""
  k_private_key: ""
  alipay_public_key: ""
  k_server_domain: "http://127.0.0.1:9999"  # 支付重定向域名
